name = "CanDecomp"
uuid = "6c57e878-bc0a-5706-8331-d2cb71f7d6e8"
version = "0.4.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Mads = "d6bdc55b-bd94-5012-933c-1f73fc2ee992"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Ipopt = "^0"
JuMP = "^0"
Mads = "^0.10"
Optim = "^0, 1.2"
StaticArrays = "^0"
julia = "^1.4"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test", "Random"]
